[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:31 Testcase test_CredKart_User_Login_Excel_DDT_004 is started
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:33 Opening Browser
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:36 Going to CredKart URL ->https://automation.credence.in/login
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:38 Reading data from Excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:39 Reading the number of rows from Excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:42 Number of rows in Excel is :  7
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 2 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@123
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:59 User 'Credencetest@test.com' is  logged in and actual result is : login_pass
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:60 Taking Screenshot for Pass
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 3 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com1
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@123
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:64 User 'Credencetest@test.com1' is not logged in and actual result is : login_fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:65 Taking Screenshot for Fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 4 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@1231
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:64 User 'Credencetest@test.com' is not logged in and actual result is : login_fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:65 Taking Screenshot for Fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 5 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com1
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@1231
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:64 User 'Credencetest@test.com1' is not logged in and actual result is : login_fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:65 Taking Screenshot for Fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 6 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@123
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:59 User 'Credencetest@test.com' is  logged in and actual result is : login_pass
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:60 Taking Screenshot for Pass
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:45 Reading data from row number : 7 in excel
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:50 Entering email :Credencetest@test.com1
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:52 Entering password :Credence@1231
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:54 Clicking Login button
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:56 Verify User is logged in or not
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:64 User 'Credencetest@test.com1' is not logged in and actual result is : login_fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:65 Taking Screenshot for Fail
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:84 Testcase test_CredKart_User_Login_Excel_DDT_004 is Pass
[32mINFO    [0m root:test_CredKart_User_login_Excel_DDT_002.py:85 Testcase test_CredKart_User_Login_Excel_DDT_004 is completed